### ISSUE TITLE
Material Folder is not copied.

### ISSUE THREAD

**Issue by mv4manishverma** [xopto/pyxopto#9] opened 2023-02-06 11:12 UTC
Hi,
I installed pyxopto on macOS apple silicon.
I tried to run the basic scripts but it gave error showing that it could not find materials folder in the path.
I then manually copied the materials folder to the installed directory and it works fine.

**Comment by xopto** [comment] 2023-02-06 18:05
Thank you for the feedback. It seems that the issue is related to all data files. A fix will be included with the next commit. In the meantime, a copy/paste of the data folder from the source distribution should fix the issue.

**Comment by mv4manishverma** [comment] 2023-02-06 18:08
> Thank you for the feedback. It seems that the issue is related to all data files. A fix will be included with the next commit. In the meantime, a copy/paste of the data folder from the source distribution should fix the issue.

Thanks. Do you have any plan to support it on apple silicon as well?

**Comment by xopto** [comment] 2023-02-06 23:11
Apple has decided to abandon/deprecate support for OpenCL and instead introduced Metal API (Metal Shading Language). I do not have any first-hand experience with the current version of macOS and OpenCL/PyOpenCL (it seems that people are running OpenCL code on M1) Porting pyxopto to Metal would require quite some work. The kernels would have to be rewritten and the Python code reorganized to allow arbitrary backends (e.g. OpenCL, and Metal). Python bindings of Metal also seem to be much less mature than PyOpenCL. There is also a concern that Apple might at some point abandon Metal as it did OpenCL. At the moment we do not have plans to replicate the pyxopto kernel code in the Metal Shading Language.

**Comment by mv4manishverma** [comment] 2023-02-07 06:12
> Apple has decided to abandon/deprecate support for OpenCL and instead introduced Metal API (Metal Shading Language). I do not have any first-hand experience with the current version of macOS and OpenCL/PyOpenCL (it seems that people are running OpenCL code on M1) Porting pyxopto to Metal would require quite some work. The kernels would have to be rewritten and the Python code reorganized to allow arbitrary backends (e.g. OpenCL, and Metal). Python bindings of Metal also seem to be much less mature than PyOpenCL. There is also a concern that Apple might at some point abandon Metal as it did OpenCL. At the moment we do not have plans to replicate the pyxopto kernel code in the Metal Shading Language.

Thanks, understood.

**Closed** 2023-08-13 00:00 UTC
Labels: bug
